#version: '3'
#services:
#  app:
#    image: heroesapp:latest  # Use the image name from the Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    env_file:
#      - .env
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
version: '3'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "mydb", "-U", "myuser" ]
      interval: 5s
      timeout: 5s
      retries: 5
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

#volumes:
#  postgres-data:

